Use constranits for api-ref target
It should be ok to use zuul-cloner these days. [1]
This would avoid docutils 0.13.1, which seems to cause the following
TypeError.

    Exception occurred:
      File "/home/jenkins/workspace/gate-neutron-lib-api-ref/.tox/api-ref/local/lib/python2.7/site-packages/docutils/writers/html4css1/__init__.py", line 288, in write_colspecs
        width += node['colwidth']
    TypeError: unsupported operand type(s) for +=: 'int' and 'str'

[1] I8f45a53429b9fcbf3689a268f096afdf5f32f461

Closes-Bug: #1649079
Change-Id: Id75e88f5031aeab21b2158c721881bf2da4a0d28