Fix mypy error caused by new oslo.utils release
oslo.utils introduced a few new typing definitions causing the error
below.

neutron_lib/db/resource_extend.py:84: error:
Unused "type: ignore" comment

Change-Id: Ifad03245554ef7fdac520734fda546f2cb641b60
Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>